project 'YJSPayManagerDemo.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YJSPayManagerDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ApplePay_SDK'
  pod 'WeChat_SDK_iOS'
  pod 'Alipay_SDK_iOS'
  pod 'UnionPay_SDK_iOS'
#  pod 'FBRetainCycleDetector'
  # Pods for YJSPayManagerDemo

  target 'YJSPayManagerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YJSPayManagerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
